title: MNPK-01
description: An 8-bit microcomputer from logic gates to a printed circuit board
url: https://krivanikm.github.io
baseurl: /mnpk01-soc
lang: en
markdown: kramdown
defaults:
  - scope:
      path: ""
    values:
      layout: default
